//
// Created by kvto on 9/15/24.
//

#ifndef SHOTMD_SHOTMD_H
#define SHOTMD_SHOTMD_H

#include <QMainWindow>
#include <QLabel>
#include <QPixmap>
#include <QPoint>



QT_BEGIN_NAMESPACE
namespace Ui { class shotmd; }
QT_END_NAMESPACE

class shotmd : public QMainWindow {
Q_OBJECT

public:
    explicit shotmd(QWidget *parent = nullptr);

    ~shotmd() override;
    void keyPressEvent(QKeyEvent *event) override;

private:
    struct Selection {
        QPoint origin;
        QPoint current;
        bool active { false };
        QRect rect() const { return QRect(origin, current).normalized(); }
        void reset() { active = false; }
    } selection;

    QPixmap originalPixmap;         // Captured full screen
    QLabel *screenshotLabel { nullptr }; // Display widget
    Ui::shotmd *ui;                 // Autogenerated UI (minimal use)

    void mousePressEvent(QMouseEvent *event) override;
    void mouseReleaseEvent(QMouseEvent *event) override;
    void mouseMoveEvent(QMouseEvent *event) override;

    void updateOverlay();                 // redraw selection rectangle
    void captureRegion(const QRect &r);   // actual capture & save
    void shot(const QPoint Tl, const QPoint RD); // legacy kept (delegates)
};


#endif //SHOTMD_SHOTMD_H
